### ISSUE TITLE
Route from data.gov.uk/data/api to server.

### ISSUE THREAD

**Issue by rossjones** [datagovuk/apiserver#24]

**Comment by davidread** [comment]
Starting to appear at https://test.data.gov.uk/data/api/

**Comment by rossjones** [comment]
Assets now being served (apart from logo) - but we're relying on hostname to build the URL.  Need to:
- change domain in deploy to test.data.gov.uk 
- Use // for protocols so we are not specific as to http or https.

**Comment by rossjones** [comment]
Doesn't route websockets but we don't _really_ need them and that will tie us to the fate of the main server (with a long-lived connection).

**Comment by rossjones** [comment]
Need to fix the Host headers so we can avoid mix-security warnings.
