### ISSUE TITLE
It should be possible to have a no parameter query

### ISSUE THREAD

**Issue by morty** [datagovuk/apiserver#35]
A dataset might be so small or boring that all you want to do is list everything.

Currently the front end doesn't have a way to show this on the basic tab. If there is no parameter then there is no query button.

**Comment by rossjones** [comment]
Sounds like a bug, either in the templating or in the thing that decides whether to show it.

**Comment by morty** [comment]
This is what it looks like for me:

![naptan-airports](https://cloud.githubusercontent.com/assets/3272/10717954/afbf4bf2-7b5e-11e5-8718-09996e580500.png)

**Comment by rossjones** [comment]
A missing match in api_view.ex
