### ISSUE TITLE
Tidy up resources for CI/proper release

### ISSUE THREAD

**Issue by rossjones** [datagovuk/apiserver#42]
So we can build releases properly

**Comment by rossjones** [comment]
So that we can use an exrm release we need to:
- Move distincts out of priv folder
- ~~Remove the need for DGU_ETL_CONFIG entirely~~

**Comment by davidread** [comment]
https://semaphoreci.com/ross/apiserver
Tests e.g. https://github.com/datagovuk/apiserver/blob/master/test/manifest/manifest_test.exs
