### ISSUE TITLE
Transport theme filter

### ISSUE THREAD

**Issue by theresnotime** [datagovuk/apiserver#57]
Just tried calling [//data/api/service/transport/planned_road_works/road?reference_number=972963](https://data.gov.uk/data/api/service/transport/planned_road_works/road?reference_number=972963) to return a planned road works with the reference of 972963 and got `{"success":true,"result":[]}` instead - can you not filter like this on the transport theme?

**Comment by rossjones** [comment]
The 'filter-on-anything' link isn't really exposed anywhere, you probably actually want...

https://data.gov.uk/data/api/service/transport/planned_road_works?reference_number=972963

Just to clarify why, the /road part at the end is the name of the pre-defined query that's meant to simplify discovery - some of them have more than one value (for instance) to be passed.  Could definitely do with cleaning up :)

**Comment by theresnotime** [comment]
Perfect, thanks for the quick reply! Might it be worth adding a reference to this in the docs? :smile:
