### ISSUE TITLE
National Public Transport Access Nodes (NaPTAN) - Railway Stations - reversed lat long

### ISSUE THREAD

**Issue by maxcbc** [datagovuk/apiserver#61]
Hi,
I seem to only get the right results from your API when I pass in the lat and long the wrong way round, i.e. passing the longitude as the latitude an vice versa.

for example I'm calling 
`http://data.gov.uk/data/api/service/transport/naptan_railway_stations/nearest?lat=-2.2346931&lon=53.4751092`

and getting back the results for Manchester (where I am). However the position in the query is actually in the Indian Ocean just north of the Seychelles. [http://www.latlong.net/c/?lat=-2.2346931&long=53.4751092](url)

Just thought I'd flag it.

**Comment by rossjones** [comment]
Thanks, this is 'probably' an ETL error when importing.  Will check.  /cc @morty

**Comment by morty** [comment]
No, I think @maxcbc is right. Will make a fix ASAP.

**Comment by rossjones** [comment]
@maxcbc this should be fixed and deployed now. 

```
https://data.gov.uk/data/api/service/transport/naptan_railway_stations/nearest?lon=-2.2346931&lat=53.4751092
```

brings back Picadilly as the first result.
