### ISSUE TITLE
Is the data API currently limited to health and transport?

### ISSUE THREAD

**Issue by gick** [datagovuk/apiserver#62]
I would be interested to parse the legislation as well,
Best

**Comment by rossjones** [comment]
At the moment yet, we're just trying things out and haven't done any ETL for anything else.  Is there a particular legislation dataset you're interested in? We're only taking datasets from data.gov.uk so would have to be something from there.

**Comment by gick** [comment]
Thank for answering, I am trying to access data in  from legislation.gov.uk. Which I think exist at least in part at data.gov.uk because the request https://data.gov.uk/data/search?res_format=RDF&q=legislation.data.gov.uk returns results.

**Comment by davidread** [comment]
Closing, as this is not an issue.

**Comment by davidread** [comment]
Please use the contact form, if you don't mind
